#!/bin/bash
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="Fluxbox"
export XDG_MENU_PREFIX="fluxbox-"
export XDG_RUNTIME_DIR=/tmp/runtime-vncuser

mkdir -p "$XDG_RUNTIME_DIR"
chmod 0700 "$XDG_RUNTIME_DIR"

dbus-daemon --fork --session --address=unix:path=/tmp/dbus-session

fluxbox &

wait